## Numpy Tutorial
Originally from DataLore Lab
https://www.datalorelabs.com

In [1]:
import numpy as np

### Arrays
A numpy array is a analogous to python list but the elements of the array should be of same type.

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

The type of the array is called numpy.ndarray . ( numpy n-dimensional array)

In [3]:
type(a)

numpy.ndarray

We associate numpy arrays with two properties shape and rank, which describe the array about the
dimension and shape it is of.

a is one dimensional array with 3 elements

In [4]:
print("Rank of a: ", a.ndim)
print("Shape of a: ", a.shape)
print("Total number of elements in the array: ", a.size)
print("Data type of the elements of a:", a.dtype)

Rank of a:  1
Shape of a:  (3,)
Total number of elements in the array:  3
Data type of the elements of a: int64


In [5]:
print(a[0], a[1], a[2]) # Prints "1 2 3"
a[0] = 5 # Change an element of the array
print(a)

1 2 3
[5 2 3]


In [6]:
b=np.array([[1., 2., 3.], [ 4., 5., 6.]])

In [7]:
print("Rank of b: ", b.ndim)
print("Shape of b: ", b.shape)
print("Total number of elements in b: ", b.size)
print("Data type of the elements of b:", b.dtype)

Rank of b:  2
Shape of b:  (2, 3)
Total number of elements in b:  6
Data type of the elements of b: float64


In [8]:
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [9]:
# accessing elements
print(b[0, 0], b[0, 1], b[1, 0]) # Prints "1 2 4"

1.0 2.0 4.0


### Array Creation
Numpy provides lots of ways to create a numpy array.

In [10]:
a = np.zeros((3,3)) # Create an array of all zeros
print(a) 

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [11]:
a = np.ones((2,5)) # Create an array of all ones
print(a) 

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [12]:
c = np.zeros_like(a) # Create an array of all zeros like a's shape
print(c)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [13]:
c = np.ones_like(b) # Create an array of all ones like b's shape
print(c)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [14]:
#numpy full
d = np.full((2,2), 10) # Create a constant array
print(d) # Prints "[[ 7. 7.]
 # [ 7. 7.]]

[[10 10]
 [10 10]]


In [15]:
#numpy eye (Identity)
e = np.eye(3) # Create a 3x3 identity matrix
print(e) 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [16]:
#numpy random
f = np.random.random((2,2)) # Create an array filled with random values
print(f)

[[ 0.38366394  0.55735735]
 [ 0.38179022  0.44332079]]


In [17]:
#numpy arange
np.arange(0, 10, 1) # arguments: start, stop, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#numpy linspace
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [19]:
#loading from file Doesnt work
#need to make file
%%file mydata.dat

SyntaxError: invalid syntax (<ipython-input-19-afaa177b6fc9>, line 3)

In [ ]:
Writing mydata.dat

In [ ]:
np.genfromtxt("mydata.dat",)

In [ ]:
np.genfromtxt("mydata.dat",)

In [ ]:
# Find more
?np.genfromtxt

You can read more about array creation in the documentation
(http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

## Array Indexing
Numpy offers several ways to index into arrays.
Slicing
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python
sequences.

In [ ]:
a = np.linspace(0, 500, 6)
print(a)

In [ ]:
# Elements at the middle of the array
a[2:4]

In [ ]:
# Last element
a[-1]

In [ ]:
# Last two elements
a[-2:]

Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by
commas. When accessing multidimensional arrays, we must specify a slice for each dimension of the array

In [ ]:
a =np.array([
 np.linspace(1, 3, 3),
 np.linspace(4, 6, 3),
 np.linspace(7, 9, 3)
])
print(a)

In [ ]:
print("First element: ", a[0,0])

When fewer indices are provided than the number of axes, the missing indices are considered complete
slices

In [ ]:
print("First row:\n", a[0])

In [ ]:
print("Upper Right 2x2 matrix:\n", a[0:2, 1:])
print("Lower Right 2x2 matrix:\n", a[1:, 1:])

In [ ]:
print("Upper Left 2x2 matrix:\n", a[:2, :2])
print("Lower Left 2x2 matrix:\n", a[1:, :2])

In [ ]:
## Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)

In [ ]:
print(a[bool_idx])

In [ ]:
# We can do the above operation in single line:
print(a[a > 2])

In [ ]:
Read More on indexing here (https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

## Other function to subset an array
### where
Convert conditional indices to position index using the where function

In [ ]:
print(a, "\n")
m, n = np.where(a > 2)
print("Axis-0: ", m)
print("Axis-1: ",n)

In [ ]:
a[m,n]

In [ ]:
# diag
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print("A:\n", A)
np.diag(A)

In [ ]:
# reverse diagonal
A[:, ::-1]

In [ ]:
np.diag(A[:, ::-1])

### Take

In [ ]:
v = np.arange(-3,3)
v

### indexing via a list

In [ ]:
row_indices = [1, 3, 5]
v[row_indices]

### Doesn’t work with List

In [ ]:
[-3, -2, -1, 0, 1, 2][row_indices]

Works like a charm!

In [ ]:
np.take([-3, -2, -1, 0, 1, 2], row_indices)

## Linear Algebra
### Elementwise-array operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
Elementwise addition; both produce the array

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y, "\n")
print(np.add(x, y))

In [ ]:
#Elementwise difference; both produce the array
print(x - y, "\n")
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y, "\n")
print(np.multiply(x, y))

In [ ]:
#Elementwise division; both produce the array
print(x / y, "\n")
print(np.divide(x, y))

In [ ]:
#Other Useful Elementwise Operations
print("Squaring...\n")
print("a: \n", a)
print("\na**2: \n", a**2)
print("\nnp.square(a): \n", np.square(a))

Same operation on python list raises an error.

In [ ]:
list_a = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
list_a**2

In [ ]:
print("exp(a):\n", np.exp(a))

In [ ]:
print("a**1.2:\n", np.power(a, 1.2))

In [ ]:
print("Natural logarithm: \n", np.log(a))
print("\nBase10 logarithm: \n", np.log10(a))
print("\nBase2 logarithm: \n", np.log2(a))

## Vector Operations
We can use the usual arithmetic operators to multiply, add, subtract, and divide vectors with scalar
numbers.

In [ ]:
v1 = np.arange(0, 5)
v1

In [ ]:
print(v1 * 2)
print(v1 / 2)
print(v1 ** 2)
print(v1 * v1)

Inner Product

In [ ]:
v2 = np.arange(5, 10)
v2

In [ ]:

v1 = [0, 1, 2, 3, 4]
v2 = [5, 6, 7, 8, 9]
#v1 . v2 = 0∗5+1 ∗ 6 + 2 ∗ 7 + 3 ∗ 8 + 4 ∗ 9
np.dot(v1, v2)

Vector Magnitude (self inner product)

In [ ]:
sum = 0
for each element in vector:
 sum += element * element

In [ ]:
np.sum([element*element for element in v1])

In [ ]:
## should work
print(v1 @ v1)

## Matrix Algebra

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

Transpose

In [ ]:
A.T

## Matrix-Vector Multiplication

In [ ]:
v1

v1 is multiplied to each row

In [ ]:
A * v1

In [ ]:
# Elementwise Matrix Multiplication
A * A

In [ ]:
#Matrix Multiplication
A.dot(A)

In [ ]:
A@A

Alternatively we can cast the array to Matrix , which enables normal arithmatic opertions to perform
matrix algebra.

In [ ]:
A_mat = np.matrix(A)
v = np.matrix(v1).T # make it a column vector
print("Matrix A:\n", A_mat)
print("\nVector v:\n",v)

In [ ]:
type(A_mat)

In [ ]:
A_mat * A_mat

In [ ]:
v.T * A_mat

In [ ]:
A_mat * v

In [ ]:
#If we try to add, subtract or multiply objects with incomplatible shapes we get an error:
v = np.matrix([1,2,3,4]).T
A_mat.shape, v.shape

In [ ]:
## This should pop an error 
A_mat * v

## Other Useful Functions
Sum

In [ ]:
A

In [ ]:
A.sum()

In [ ]:
# Column-wise sum or Reduce by row
A.sum(axis=0)

In [ ]:
# Row-wise sum or Reduce by column
A.sum(axis=1)

### Statistics

Mean

In [ ]:
print("Mean of A: \n", A.mean())
print("Column-wise mean of A: \n", A.mean(axis=0))
print("Row-wise mean of A: \n", A.mean(axis=1))

In [ ]:
# Variance
print("Variance of A: \n", A.var())
print("Column-wise variance of A: \n", A.var(axis=0))
print("Row-wise variance of A: \n", A.var(axis=1))

In [ ]:
# Standard deviation
print("Standard Deviation of A: \n", A.std())
print("Column-wise Standard Deviation of A: \n", A.std(axis=0))
print("Row-wise Standard Deviation of A: \n", A.std(axis=1))

In [ ]:
#Min and Max
print("Minimum of A: \n", A.min())
print("Column-wise Minimum of A: \n", A.min(axis=0))
print("Row-wise Minimum of A: \n", A.min(axis=1))

In [ ]:
print("Maximum of A: \n", A.max())
print("Column-wise Maximum of A: \n", A.max(axis=0))
print("Row-wise Maximum of A: \n", A.max(axis=1))

## Broadcasting
source: Justin Johnson (http://cs.stanford.edu/people/jcjohns/)

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when
performing arithmetic operations.
For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like
this:

In [ ]:
X = np.array([[1,2],[3, 4] ,[5,6], [7,8]])
v = np.array([1, 2])
print("X: \n", X)
print("\nv:\n", v)

We can add the vector v to each row of the matrix x, storing the result in the matrix y

In [ ]:
Y = np.zeros_like(X)
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
 Y[i, :] = X[i, :] + v
print(Y)

Adding v to every row of matrix X is equivalent to form a matrix vv by stacking multiple copies of v
vertically, then performing elementwise summation of X and vv

In [ ]:
vv = np.tile(v, (4, 1)) # stack four rows of v
print("Stacked vectors: \n", vv)
Y = X + vv # Add x and vv elementwise
print("\nResult: \n", Y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v .
Subject to certain constraints, the smaller array is broadcast across the larger array so that they have
compatible shapes.

In [ ]:
Y = X + v # Add v to each row of x using broadcasting
print(Y)

Broadcasting two arrays together follows these rules:
1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both
shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension,
or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of
shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first
array behaves as if it were copied along that dimension
For more on broadcasting please read Eric’s Broadcasting Docs (http://scipy.github.io/oldwiki/pages/EricsBroadcastingDoc)
or the documentation
(https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

In [ ]:
v = np.array([1])
print("Rank of v: ", v.ndim)
X + v

Compute outer product of vectors
To compute an outer product, we first reshape v to be a column vector of shape (3, 1) . We can then
broadcast it against w to yield an output of shape (3, 2) , which is the outer product of v and w :

In [ ]:
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
print(np.reshape(v, (3, 1)) * w)

## Array Reshape, Concatenation, Stacking and Copy
### Reshape

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

In [ ]:
m, n = A.shape
B = A.reshape((1, m*n))
print(B.shape)
print(B)

In [ ]:
B[0, 0:5] = -1

In [ ]:
A

In [ ]:
B = A.flatten()
print(B.shape)
print(B)

In [ ]:
B[0:5] = 10
B

In [ ]:
A

### Concatenation and Stacking
Join a sequence of arrays along an existing axis.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b.T), axis=1)

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b.T))

### Copy
To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is
important for example when objects are passed between functions, to avoid an excessive amount of
memory copying when it is not necessary (technical term: pass by reference).

In [ ]:
A = np.array([[1, 2], [3, 4]])
A

In [ ]:
# now B is referring to the same array data as A
B = A
# changing B affects A
B[0,0] = 10
B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object B copied
from A , then we need to do a so-called “deep copy” using the function copy :

In [ ]:
B = A.copy()
# now, if we modify B, A is not affected
B[0,0] = -5
B

In [ ]:
A

Further Reading
- http://numpy.scipy.org (http://numpy.scipy.org)
- http://scipy.org/Tentative_NumPy_Tutorial (http://scipy.org/Tentative_NumPy_Tutorial)
- http://scipy.org/NumPy_for_Matlab_Users (http://scipy.org/NumPy_for_Matlab_Users) - A Numpy
guide for MATLAB users