## Pytorch tutorial
http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

To setup an initial understanding.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00 -7.4668e+00
 4.5673e-41 -5.3806e-02  4.5673e-41
-2.6815e+06  4.5673e-41 -2.6815e+06
 4.5673e-41 -3.2452e+06  4.5673e-41
-3.1552e+06  4.5673e-41 -1.1177e-01
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)


 0.8180  0.1831  0.6580
 0.3410  0.1037  0.8664
 0.9746  0.2583  0.8823
 0.7392  0.4272  0.1205
 0.6209  0.0127  0.6182
[torch.FloatTensor of size 5x3]



Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. Let’s see addition as an example

Addition: syntax 1

In [5]:
y = torch.rand(5, 3)
print(x + y)


 1.2339  0.3642  1.2537
 0.4079  0.3407  1.8247
 1.7992  0.4524  1.6935
 1.0790  0.5248  0.9662
 1.1204  0.0545  1.3213
[torch.FloatTensor of size 5x3]



Addition: syntax 2

In [6]:
print(torch.add(x, y))


 1.2339  0.3642  1.2537
 0.4079  0.3407  1.8247
 1.7992  0.4524  1.6935
 1.0790  0.5248  0.9662
 1.1204  0.0545  1.3213
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor

In [7]:
result = torch.Tensor(5, 3)
## watch the out for result
torch.add(x, y, out=result)
print(result)


 1.2339  0.3642  1.2537
 0.4079  0.3407  1.8247
 1.7992  0.4524  1.6935
 1.0790  0.5248  0.9662
 1.1204  0.0545  1.3213
[torch.FloatTensor of size 5x3]



Addition: in-place

In [8]:
# adds x to y
y.add_(x)
print(y)


 1.2339  0.3642  1.2537
 0.4079  0.3407  1.8247
 1.7992  0.4524  1.6935
 1.0790  0.5248  0.9662
 1.1204  0.0545  1.3213
[torch.FloatTensor of size 5x3]



In [15]:
print(x)
### prints [every row , 2nd column]
print(x[:, 1])
### prints [2nd row , all columns]
print(x[1, :])
### prints [2nd row , all columns]
print(x[1, :1])


 0.8180  0.1831  0.6580
 0.3410  0.1037  0.8664
 0.9746  0.2583  0.8823
 0.7392  0.4272  0.1205
 0.6209  0.0127  0.6182
[torch.FloatTensor of size 5x3]


 0.1831
 0.1037
 0.2583
 0.4272
 0.0127
[torch.FloatTensor of size 5]


 0.3410
 0.1037
 0.8664
[torch.FloatTensor of size 3]


 0.3410
[torch.FloatTensor of size 1]



## Converting torch Tensor to numpy Array

In [14]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [15]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [16]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


## Converting numpy Array to torch Tensor
See how changing the np array changed the torch Tensor automatically

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensors
Tensors can be moved onto GPU using the .cuda function.

In [22]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

print(x)


 0.2582  0.4529  0.1641
 0.5981  0.5377  0.0012
 0.4543  0.0688  0.0840
 0.7876  0.0048  0.8325
 0.8351  0.6137  0.0908
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]



# Part 2